### ISSUE TITLE
Upgrade play-geojson to support play2.8

### ISSUE THREAD

**Issue by ramdasbb** [jroper/play-geojson#34]
Is there a plan to make play-geojson available for play 2.8?

After updating play-JSON lib to 2.8 it's giving the following error.

No Json serializer found for type au.id.jazzy.play.geojson.Feature[au.id.jazzy.play.geojson.LatLng]. Try to implement an implicit Writes or Format for this type.
No Json serializer found for type au.id.jazzy.play.geojson.Geometry[au.id.jazzy.play.geojson.LatLng]. Try to implement an implicit Writes or Format for this type.

**Comment by ceecer1** [comment]
@ramdasbb were you able to resolve the issue you pointed?

**Comment by jroper** [comment]
The issue was that play-json 2.8.x changed `Writes` to be invariant instead of contravariant, so the implicit `GeoJson` writes that was available was no longer a candidate for subtypes in implicit resolution. I've fixed this in #35, by making an implicit writes available for each subtype. And I've just kicked off a release build for play-geojson 1.7.0 which contains the fix.

**Comment by ramdasbb** [comment]
Yes, my issue got resolved.

Thanks a lot.
__

Regards,

Ramdas Bhingole.

Software Engineer,

+91 8975504842.
